---
#-------------------------------
# General Site Settings

title: Welcome to My portfolio 
logo:
author: themefisher
description: this is meta description
email: mario.flores-orihuela@etu.univ-grenoble-alpes.fr
phone: +33 06 19 94 61 47
address: 351 allée Berlioz Saint Martin D'Hères, France
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Mario <br> Embedded Systems Engineer 

social:
  - { icon: "ti-linkedin", link: "https://linkedin.com/in/mario-jesus-flores-orihuela-2756621b8" }
  - { icon: "ti-github", link: "https://github.com/mriflores" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/mfloresorihuela/" }
#-------------------------------
# About (Section and Page)

# About Section
blurb: You're viewing my portfolio. You're here perhaps because you liked my profile and are interested in learning more about me. Here you can get to know me better and see more of my work up to this point, as well as how I've improved over the years.
blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page
# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Taking time to understand the project requirements, conducting research, and creating a detailed plan to ensure a successful outcome."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Design is hard, becuase it requires creativity and technical skills. I always want to changes everything to be perfect, but I know that the most important is to deliver a good product in time. So I try to find a balance between design and development."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Once the design and development phases are complete, I focus on delivering a high-quality product that meets all requirements and is ready for deployment."

# My Team Section
#team:
  #- title: "Jack Schenziwe"
  #  image: "assets/images/team/member-1.png"
  #  designation: "Project Manager"

  #- title: "Julias Carlie"
  #  image: "assets/images/team/member-2.png"
  #  designation: "Web Developer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: C/C++, color: "#fdb157", value: "95%" }
  - { name: PCB Design, color: "#9473e6", value: "90%" }
  - { name: FPGA, color: "#bdecf6", value: "85%" }
  - { name: Embedded and IOT, color: "#ffbcaa", value: "95%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Final Proyect Team member,
      icon: "icon-3.png",
      date: "January 2026 - Present",
      organization: "Technology and Strategy",
    }
  - {
      name: Internship Electronic Circuit Design,
      icon: "icon-1.png",
      date: "April 2025 - August 2025",
      organization: "Rivinnov",
    }
  - {
      name: Internship in Computer Vision,
      icon: "icon-2.png",
      date: "June 2024 - Aug 2024",
      organization: "ArcelorMittal",
    }
  #-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Master’s in Computer Science and Electronics for Embedded Systems,
      date: "2026",
      organization: "Polytech Grenoble",
    }
  - {
      name: Licence Sciences pour l'Ingénieur specialized in Electronics and Automation ,
      date: "2023",
      organization: "Aix-Marseille University",
    }
  - {
      name: Licence in Information Technology and Systems Engineering,
      date: "2021",
      organization: "ESAN university",
    }

#-------------------------------
# Services Section

services-title: My core activiities
services:
  - {
      name: PCB Design,
      icon: ti-palette,
      description: "I have worked on various PCB design projects, utilizing tools such as Altium Designer and KiCad to create efficient and reliable circuit layouts",
      active: false,# Add true to select section
    }
  - {
      name: Firmware Development,
      icon: ti-vector,
      description: "I have experience in developing firmware for embedded systems, using programming languages such as C and C++ to create efficient code for microcontrollers and other embedded devices.",
      active: true, # Add true to select section
    }
  - {
      name: Embedded Systems,
      icon: ti-panel,
      description: "I have worked on various embedded systems projects using microcontrollers such as Arduino, Raspberry Pi, STMicrocontrollers, and ESP32, as well as experience with real-time operating systems (RTOS) and low-level programming.",
      active: false,# Add true to select section
    }
  - {
      name: FPGA Design,
      icon: ti-panel,
      description: "I have worked on various FPGA design projects using tools such as Vivado, implementing digital logic and designing custom hardware",
      active: true,# Add true to select section
    }
  - {
      name: Machine Learning,
      icon: ti-panel,
      description: "I have worked on various machine learning projects using Python and libraries such as TensorFlow and PyTorch, implementing algorithms for data analysis and predictive modeling.",
      active: false,# Add true to select section
    }
  - {
      name: Version Control,
      icon: ti-panel,
      description: "I have experience using version control systems such as Git to manage code changes, collaborate with team members, and maintain project history.",
      active: true,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/My-portfolio/2025/05/26/PAMI_VF/"

  - image: "assets/images/portfolio/item-2.png"
    url: "/My-portfolio/2024/05/26/PAMI/"

  - image: "assets/images/portfolio/item-3.png"
    url: "/My-portfolio/2025/05/26/PAMI_VF/"

  - image: "assets/images/portfolio/item-4.png"
    url: "/My-portfolio/2025/05/26/rivinnov/"

  - image: "assets/images/portfolio/item-5.png"
    url: "/My-portfolio/2025/12/12/FPGA/"

  - image: "assets/images/portfolio/item-6.png"
    url: "/My-portfolio/2025/11/17/FREE_RTOS/"

# Portfolio Page
portfolio-label:
  - { title: "Embedded Systems & Firmware", type: "code" }
  - { title: "Hardware & Digital Design", type: "hardware" }
  
portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "/My-portfolio/2025/05/26/PAMI_VF/"
    portfolio-type:
      - type: "code"
      - type: "hardware"

  - image: "assets/images/portfolio/item-2.png"
    url: "/My-portfolio/2024/05/26/PAMI/"
    portfolio-type:
      - type: "code"
      - type: "hardware"

  - image: "assets/images/portfolio/item-3.png"
    url: "/My-portfolio/2025/05/26/PAMI_VF/"
    portfolio-type:
      - type: "hardware"

  - image: "assets/images/portfolio/item-6.png"
    url: "/My-portfolio/2025/11/17/FREE_RTOS/"
    portfolio-type:
      - type: "code"

  - image: "assets/images/portfolio/item-5.png"
    url: "/My-portfolio/2025/12/12/FPGA/"
    portfolio-type:
      - type: "code"

  - image: "assets/images/portfolio/item-8.png"
    url: "/My-portfolio/2026/01/26/simulateur/"
    portfolio-type:
      - type: "hardware"

  - image: "assets/images/portfolio/item-4.png"
    url: "/My-portfolio/2025/05/26/rivinnov/"
    portfolio-type:
      - type: "hardware"

  - image: "assets/images/portfolio/item-9.png"
    url: "/My-portfolio/2023/02/17/ECG/"
    portfolio-type:
      - type: "hardware"

  - image: "assets/images/portfolio/item-11.png"
    url: "/My-portfolio/2024/05/26/Spot/"
    portfolio-type:
      - type: "code"

  - image: "assets/images/portfolio/item-12.png"
    url: "/My-portfolio/2025/05/26/low-consumption/"
    portfolio-type:
      - type: "code"

#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"

#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

#contact-title: Contact Info
#contact-email: mario.flores-orihuela@etu.univ-grenoble-alpes.fr
